# Generated by Django 4.2.4 on 2023-08-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=35)),
                ('company_observed', models.CharField(max_length=20)),
                ('activity_observed', models.CharField(choices=[('Lifting/Rigging', 'Lifting/Rigging'), ('Piping', 'Piping'), ('Electrical/Instrument', 'Electrical/Instrument'), ('Hauling (Truck Operations)', 'Hauling (Truck Operations)'), ('Scaffolding', 'Scaffolding'), ('Refueling Operations', 'Refueling Operations'), ('Inspection/Testing', 'Inspection/Testing'), ('Insulation', 'Insulation'), ('General Labor/Preservation', 'General Labor/Preservation'), ('Blasting/Coating', 'Blasting/Coating'), ('Carpentry', 'Carpentry'), ('Welding Activity/Cutting', 'Welding Activity/Cutting'), ('Structural Steel/Erection', 'Structural Steel/Erection'), ('Concrete/Grout/Masonry', 'Concrete/Grout/Masonry'), ('Office', 'Office')], max_length=30)),
                ('i_obseved', models.CharField(choices=[('UC', 'Unsafe Condition'), ('UA', 'Unsafe act'), ('PO', 'Positive observation')], default='None', max_length=24)),
                ('possible_consequences', models.CharField(choices=[('A', 'A')], default='None', max_length=24)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
            },
        ),
    ]
