# Generated by Django 4.2.4 on 2023-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='activity_observed',
            field=models.CharField(choices=[('Lifting/Rigging', 'Lifting/Rigging'), ('Piping', 'Piping'), ('Electrical/Instrument', 'Electrical/Instrument'), ('Hauling (Truck Operations)', 'Hauling (Truck Operations)'), ('Scaffolding', 'Scaffolding'), ('Refueling Operations', 'Refueling Operations'), ('Inspection/Testing', 'Inspection/Testing'), ('Insulation', 'Insulation'), ('General Labor/Preservation', 'General Labor/Preservation'), ('Blasting/Coating', 'Blasting/Coating'), ('Carpentry', 'Carpentry'), ('Welding Activity/Cutting', 'Welding Activity/Cutting'), ('Structural Steel/Erection', 'Structural Steel/Erection'), ('Concrete/Grout/Masonry', 'Concrete/Grout/Masonry'), ('Office', 'Office')], default=None, max_length=27),
        ),
    ]
