# Generated by Django 4.2.4 on 2023-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default=9009, max_length=60),
            preserve_default=False,
        ),
    ]
