# Generated by Django 4.2.4 on 2023-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0002_alter_survey_if_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
