# Generated by Django 4.2.4 on 2023-08-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0003_alter_survey_corrective_measures_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='i_obseved',
            new_name='i_observed',
        ),
    ]
