# Generated by Django 4.2.4 on 2023-09-02 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0003_alter_survey_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 5, 34, 46, 778115, tzinfo=datetime.timezone.utc)),
        ),
    ]
