# Generated by Django 4.2.4 on 2023-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0006_alter_survey_if_reported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Allowed User',
                'verbose_name_plural': 'Allowed Users',
            },
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
