# Generated by Django 4.2.4 on 2023-09-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazid', '0007_alloweduser_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CUser', 'verbose_name_plural': 'CUsers'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Hazid', 'verbose_name_plural': 'Hazids'},
        ),
    ]
